spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password: 123456

mqtt:
  broker: tcp://127.0.0.1:1883
  client-id: flying-${random.uuid}
  username: flying
  password: 654321
  topics:
    - ${mqtt.topic.state}
    - ${mqtt.topic.osd}

mqtt.topic:
  state: thing/product/+/state
  osd: thing/product/+/osd